# application-dev.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_dev
    username: root
    password: Bn19c0248@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
